---
- name: Webserver and Alias Deployment
  hosts: dev
  become: yes
  roles:
    - webserver
  tasks:
    - name: call the jinja temaplate
      ansible.builtin.template:
        src: alias.temp.j2
        dest: /var/www/html/index.html
      notify: Restart the web services

  handlers:
    - name: Restart the web services
      ansible.builtin.service:
        name: httpd
        state: restarted

  







